modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://coolbot.carrd.co"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''${mod_description}'''
logoFile="logo.png"

[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="bots_lib"
   mandatory=true
   versionRange="3.3"
   ordering="NONE"
   side="BOTH"
